# Generated by Django 4.2.7 on 2024-08-12 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to='excel_files/'),
        ),
        migrations.CreateModel(
            name='TaskData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column1', models.CharField(max_length=255)),
                ('column2', models.CharField(max_length=255)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.task')),
            ],
        ),
    ]
