# Generated by Django 4.2.7 on 2024-08-19 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_userprogress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProgress',
        ),
    ]
