# Generated by Django 4.2.7 on 2024-08-20 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_userprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='lesson_ptr',
        ),
        migrations.RemoveField(
            model_name='taskdata',
            name='task',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='completed_sentences',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='task',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='user',
        ),
        migrations.DeleteModel(
            name='AdditionalWords',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskData',
        ),
        migrations.DeleteModel(
            name='UserProgress',
        ),
    ]
