# Generated by Django 4.2.7 on 2024-08-21 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProgress',
        ),
    ]
