# Generated by Django 4.2.7 on 2024-08-22 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='UserProgress',
        ),
    ]
