# Generated by Django 4.2.7 on 2024-08-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='can_delete',
            field=models.BooleanField(default=True),
        ),
    ]
