# Generated by Django 4.2.7 on 2024-08-29 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_lesson_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='lesson',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='UserProgress',
        ),
    ]
